services:
  php:
    container_name: php_server
    build:
      context: .
    volumes:
      - "./:/usr/app"
      # - "./php:/usr/local/etc/php/"
    ports:
      - "8085:8085"

  db:
    container_name: mariadb_server
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root

  adminer:
    container_name: adminer_server
    image: adminer
    restart: always
    ports:
      - 5000:8080
